Added ability to load Swagger JSON file into objects
marcelojaloto/SwagDoc pull request #3
Opened 2018-04-21 02:45 UTC by geoffsmith82

Hi Marcelo,

I have added the ability to load a Swagger JSON file into the objects as well.  I have also added in a few extra properties on several of your objects.

2018-04-23 03:02 UTC, marcelojaloto reviewed
@geoffsmith82,
Thank you for your collaboration.

2018-04-23 03:07 UTC, marcelojaloto commented
@cunhaw 
Could you please also check?

2018-04-23 20:05 UTC, cunhaw commented on Source/Swag.Doc.Info.pas
> +    FTermsOfService: string;
fTermsOfService

2018-04-23 20:07 UTC, cunhaw requested changes

2018-04-23 20:07 UTC, cunhaw commented on Source/Swag.Doc.Info.pas
> +  if not FTermsOfService.IsEmpty then
fTermsOfService

2018-04-23 20:07 UTC, cunhaw commented on Source/Swag.Doc.Info.pas
> +    property TermsOfService: string read FTermsOfService write FTermsOfService;
fTermsOfService

2018-04-23 23:17 UTC, cunhaw requested changes
Just small formatting issues

2018-04-23 23:17 UTC, cunhaw commented on Source/Swag.Doc.pas
> +      Schemes := self.Schemes + [tpsHttp]
Self

2018-04-23 23:17 UTC, cunhaw commented on Source/Swag.Doc.pas
> +      Schemes := self.Schemes + [tpsHttps];
Self

2018-04-23 23:17 UTC, cunhaw commented on Source/Swag.Doc.pas
> +    property License : TSwagInfoLicense read fLicense;
License: TSwagInfoLicense (remove blank space)

2018-04-23 23:17 UTC, cunhaw commented on Source/Swag.Doc.pas
> +    fLicense : TSwagInfoLicense;
fLicense: TSwagInfoLicense; (remove blank space)

2018-04-25 02:11 UTC, geoffsmith82 commented
After you have merged this PR in, I have a demo of generating a swagger file by code and some more of the swagger spec implemented.

2018-04-25 12:12 UTC, marcelojaloto approved these changes
See improvements and code pattern changes to follow in your next changes.

2018-04-25 12:12 UTC, marcelojaloto commented on Source/Swag.Doc.pas
> -    if (vJsonSchemesArray.Items[j].Value = 'http') then
See the improvements in unit Swag.Common.Types.Helpers.

2018-04-25 12:16 UTC, merged

2018-04-25 12:19 UTC, marcelojaloto commented
@geoffsmith82, 
Please make another PR for your new collaborations. Thanks!